# Generated by Django 5.0.6 on 2026-07-28 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('LOANED', 'En préstamo'), ('MAINTENANCE', 'En mantenimiento'), ('DAMAGED', 'Dañado')], default='AVAILABLE', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_equipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
