# Generated by Django 5.0.6 on 2026-07-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
