# Generated by Django 5.0.6 on 2026-08-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_list_version',
            field=models.IntegerField(default=0, help_text='Versión de lista cuando inició sesión'),
        ),
    ]
