# Generated by Django 5.0.6 on 2026-08-04 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('inventory', '0002_equipmentmodel_is_active'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Fecha bloqueada', unique=True)),
                ('reason', models.CharField(blank=True, help_text='Motivo del bloqueo', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si este bloqueo está activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocked_dates', to='authentication.usermodel')),
            ],
            options={
                'db_table': 'blocked_dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)')),
                ('start_time', models.TimeField(help_text='Hora de inicio de disponibilidad')),
                ('end_time', models.TimeField(help_text='Hora de fin de disponibilidad')),
                ('is_active', models.BooleanField(default=True, help_text='Si esta franja está activa')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='inventory.equipmentmodel')),
            ],
            options={
                'db_table': 'equipment_schedules',
                'ordering': ['equipment', 'day_of_week', 'start_time'],
                'unique_together': {('equipment', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TentativeSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('expires_at', models.DateTimeField(help_text='Fecha y hora de expiración de la agenda tentativa')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Si ya fue confirmada como préstamo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentative_schedules', to='inventory.equipmentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentative_schedules', to='authentication.usermodel')),
            ],
            options={
                'db_table': 'tentative_schedules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='tentative_s_user_id_e36757_idx'), models.Index(fields=['equipment', 'pickup_date', 'return_date'], name='tentative_s_equipme_d963f2_idx')],
            },
        ),
    ]
