# Generated by Django 5.0.6 on 2026-08-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_blockeddate_equipmentschedule_tentativeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitemmodel',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reservado'), ('LOANED', 'En préstamo'), ('RETURNED', 'Devuelto')], default='RESERVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tentativeschedule',
            name='expires_at',
            field=models.DateTimeField(help_text='Fecha y hora de expiración'),
        ),
    ]
