# Generated by Django 5.0.6 on 2026-08-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanitemmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitemmodel',
            name='return_notes',
            field=models.TextField(blank=True, help_text='Notas sobre el estado al devolver', null=True),
        ),
        migrations.AddField(
            model_name='loanitemmodel',
            name='return_status',
            field=models.CharField(choices=[('OK', 'En buen estado'), ('DAMAGED', 'Dañado'), ('MISSING', 'Faltante'), ('LATE', 'Devuelto tarde'), ('PENDING', 'Pendiente de recepción')], default='PENDING', help_text='Estado de la devolución del equipo', max_length=20),
        ),
    ]
