# Generated by Django 5.0.6 on 2026-08-06 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidUserList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(help_text='Semestre o periodo académico', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si esta lista está activa')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_lists', to='authentication.usermodel')),
            ],
            options={
                'db_table': 'valid_user_lists',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification', models.CharField(db_index=True, help_text='Cédula de identidad', max_length=20)),
                ('email', models.EmailField(db_index=True, help_text='Correo institucional', max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo en la lista actual')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='valid_users.validuserlist')),
            ],
            options={
                'db_table': 'valid_users',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('identification', 'list')},
            },
        ),
    ]
